version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.18.0.3:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
      - C:/warehouse/software/docker/docker.sock:/var/run/docker.sock
    restart: always